name: Bug
description: Something busted
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: PC / iOS / Android
