name: Task
description: A small non-feature task
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    id: what
    attributes:
      label: What
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
